language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install .
  - pip install -r requirements.txt
before_script:
  - curl -sSl https://raw.githubusercontent.com/hodgesds/travis-solr/master/travis-solr.sh | SOLR_VERSION=5.0.3 bash
script: nosetests
