language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
install:
  - pip install .
  - pip install -r requirements.txt
#services:
    #- elasticsearch
before_script:
  - sleep 15
script: nosetests
